services:
  - type: web
    name: road-object-detection
    env: python
    region: oregon  # or frankfurt, singapore, etc. (based on your location)
    plan: free

    # Build and start configuration
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0

    # Optional auto-deploy on every push
    autoDeploy: true

    # Python version (optional)
    runtime: python
